# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e38e3135376838d7e169309c0cde53b1189a98f1a6257ccea636d5f5743c2f3b1c0d964ca252fa12a9f2705bc53d5f097f183129afa2a3b06eb7d7c001f2afd1
  ipinfo_token: e946d116341447
  
test:
  secret_key_base: 03ff01a8bd80985e6a2f3420311fe6307ec810a4014fd911eba4540e90f348dc7bfbf40bcbc1b147666b8734a8490ddff83409951d0cb3429523bd8c8baa0e03
  ipinfo_token: e946d116341447
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  ipinfo_token: <%= ENV["IPINFO_TOKEN"] %>